DROP TABLE IF EXISTS "Offers";
DROP TABLE IF EXISTS "RejectedOffers";
DROP TABLE IF EXISTS "Jobs";
DROP TABLE IF EXISTS "StarRatings";
DROP TABLE IF EXISTS "LawyerProfiles";
DROP TABLE IF EXISTS "Lawyers";
DROP TABLE IF EXISTS "Bars";
DROP TABLE IF EXISTS "Cities";

